import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import ElevatorHistory from "../components/ElevatorHistory";

const Home: NextPage = () => {
  const [floor, setFloor] = useState(1);
  const [isMoving, setIsMoving] = useState(false);
  const [doors, setDoors] = useState("closed");
  const [events, setEvents] = useState([]);

  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.layoutContainer}>
        <div className={styles.leftColumn}>
          <div className={styles.card}>
            <h1>Elevator</h1>
            <div>
                Floor {floor}
            </div>
            <div>
                {isMoving?'Is moving' : 'Is not moving'}
            </div>
            <div>
                Doors are {doors}
            </div>
          </div>
        </div>
        <div className={styles.rightColumn}>
          <ElevatorHistory history={events} />
        </div>
      </div>
    </div>
  );
};

export default Home;
